spring.config.import=optional:file:.env[.properties]
spring.application.name=dungeontalk-application
spring.profiles.default=dev

# Thymeleaf \uC124\uC815
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
